### ISSUE TITLE
could you add more levels in the sonlvl ini pls i would love it

### ISSUE THREAD

**Issue by newfuckingplayer** [AlexField442/Sonic-2-Simon-Wai-Disassembly#6]

**Comment by AlexField442** [comment]
All the other levels are empty voids, so adding them to SonLVL would serve no purpose.

**Comment by newfuckingplayer** [comment]
cant you just make an copy just for me please

**Comment by Ushupiuck** [comment]
One could argue tho that for completeness’s sake, these empty levels slots should be provided so that they can be edited; for example, if someone wanted to backport Death Egg/Sky Chase/Wing Fortress from Sonic 2 final to Simon Wai

**Comment by SONIC123CDMANIA** [comment]
> One could argue tho that for completeness’s sake, these empty levels slots should be provided so that they can be edited; for example, if someone wanted to backport Death Egg/Sky Chase/Wing Fortress from Sonic 2 final to Simon Wai

Very good point.

**Comment by Endersteve8479** [comment]
I wanna know how back port those zones.

**Comment by SonicWai** [comment]
I want to recreate Cyber City Zone with the new assets
